#ifndef MOCK_IRODS_ERROR_TABLE_H
#define MOCK_IRODS_ERROR_TABLE_H

#define SYS_INVALID_INPUT_PARAM -1001
#define SYS_INTERNAL_ERR -1002
#define FILE_WRITE_ERR -1003
#define FILE_READ_ERR -1004
#define FILE_LSEEK_ERR -1005
#define UNIX_FILE_LSEEK_ERR -1006

#endif
